### ISSUE TITLE
Do you have any sample or pretrain to judge performance ?

### ISSUE THREAD

**Issue by rishikksh20** [cnlinxi/tpse_tacotron2#1]

**Comment by cnlinxi** [comment]
Sorry, I can't provide it, I use the company's server to train it.

**Comment by rishikksh20** [comment]
@cnlinxi no problem just tell me is it working fine or not?

**Comment by cnlinxi** [comment]
@rishikksh20 Honestly, I didn't find a suitable dataset to train it. I used a Chinese dataset(Biaobei Corpus) and the dataset itself is dull and the effect is not obvious.
