### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by gongchenghhu** [cnlinxi/tpse_tacotron2#2]
你好，我有两个问题想问您一下。
第一个多卡训练时，几个卡必须是连续的吗，而且第一个卡必须是0卡吗
还有一问题是我用的你的代码，但是始终学不到对齐，20万步之后也没有对齐，请问您遇到过对学习不到的问题吗
我用的是BC2013的数据，batch_size小于32
希望您能帮我提一些提建议

**Comment by cnlinxi** [comment]
Apologize for late reply:(
1. The first GPU Id does not need to be 0, but multiple GPU Ids must be continuous.
2. I train this by Biaobei, which is convergence. I look forward to a better dataset. Batch size must not be less than 32 or it will cause non convergence.

More questions are welcome
